### ISSUE TITLE
breaks with commit fd6acd38

### ISSUE THREAD

**Issue by lk251** [syxanash/bluerain#2]
Haven't diagnosed yet. I hope it's not something on my end. fd6acd38

**Comment by syxanash** [comment]
The issue should be fixed in the latest version deployed. Resizing the window will dynamically fill the space with more posts instead of reloading the entire page.
See https://github.com/syxanash/bluerain/commit/078ad52aea30c05e1c8f7857a257eb75e2b692d3#diff-44b7c9667cc5b7c4fdffe6684c4351fb6bbc36513222466b96ff0b425a49ae27R84
